# @package _global_

dataset:
  name: Wave
  in_dim: ${dataset.cls.input_length}
  edge_dim: 0
  out_dim: 1
  cls:
    _target_: external.custom_hermes.dataset.heatwave_pde.HeatWavePDEonMesh
    root: "${work_dir}/data/wave"
    pre_transform_str: ""
    processed_dir_str: "processed_train"
    maxT: 200
    num_samples: 5
    input_length: 5
    output_length: 3

loss:
  _target_: torch.nn.MSELoss

model:
  _target_: external.hermes.src.run.pde.PDERegressor

engine:
  _target_: external.hermes.src.run.pde.PDEEngine
  device: ${device}
  disable_tqdm: false
  grad_accum_steps: 1
