# @package _global_

dataset:
  name: WeatherBench 
  in_dim: 2 # this is t850 and z500
  edge_dim: 0
  out_dim: 2
  cls:
    _target_: external.custom_hermes.dataset.weatherbench.WeatherBench
    eras5_path: "${work_dir}/data/weatherbench/eras5"
    mesh_path: "${work_dir}/data/weatherbench/earth_mesh.vtp"

loss:
  _target_: torch.nn.MSELoss

model:
  _target_: external.hermes.src.run.pde.PDERegressor

engine:
  _target_: external.hermes.src.run.pde.PDEEngine
  device: ${device}
  disable_tqdm: false
  grad_accum_steps: 1
