# @package _global_

train:
  epochs: 100
  batch_size: 1
  lr: 1e-3

optimizer:
  _target_: torch.optim.Adam
  lr: ${train.lr}
  weight_decay: 1e-5

backbone:
  net:
    block_dims:
      - ${dataset.in_dim}
      - 84
      - 84
      - 84
      - ${dataset.out_dim}
    final_activation: false
