# @package _global_

train:
  epochs: 100
  batch_size: 1
  lr: 1e-2

optimizer:
  _target_: torch.optim.Adam
  lr: ${train.lr}
  weight_decay: 1e-5

backbone:
  net:
    final_activation: false
    T: 10
