# @package _global_

train:
  epochs: 100
  batch_size: 1
  lr: 1e-4

optimizer:
  _target_: torch.optim.Adam
  lr: ${train.lr}
  weight_decay: 1e-5

backbone:
  net:
    depth: 8
    dim: 5
    edge_dim: 1 # squared distance as edge feature
    m_dim: 32 