# @package _global_

train:
  epochs: 100
  batch_size: 1
  lr: 3e-4

optimizer:
  _target_: torch.optim.Adam
  lr: ${train.lr}
  weight_decay: 1e-5

backbone:
  net:
    message_dims:
      - - ${dataset.in_dim}
        - 100
        - 100
      - - 100
        - 100
        - 100
    update_dims:
      - - 100
        - 100
      - - 100
        - ${dataset.out_dim}
    edge_dims: ${dataset.edge_dim}
    final_activation: false
