# @package _global_

train:
  epochs: 1
  batch_size: 1
  lr: 7e-5

optimizer:
  _target_: torch.optim.Adam
  lr: ${train.lr}
  weight_decay: 1e-5

backbone:
  net:
    in_node_nf: 3
    hidden_nf: 64
    out_node_nf: ${dataset.out_dim}
    in_edge_nf: ${dataset.edge_dim}
    n_layers: 2
