name: SE(3)-Transformer

net:
  _target_: external.custom_hermes.backbone.se3_transformer.SE3Transformer
  heads: 2
  dim_head: 16
  num_degrees: 3
  attend_sparse_neighbors: true
  num_neighbors: 0
  attend_self: true
