name: Uni
# 590081 
net:
  _target_: external.custom_hermes.backbone.uni_gcn.Uni
  input_dim: 3
  hidden_dim: 256 
  output_dim: 1
  projection: "pad"
  num_encoder_layers: 10
  decoder: "gcn"
  num_decoder_layers: 1
  null_isolated: false
  add_self_loops: false
  dropout: false
